twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: /robot1/cmd_vel_nav
        timeout: 0.5
        priority: 10

      joystick:
        topic: teleop/cmd_vel
        timeout: 0.5
        priority: 100
